"""empty message

Revision ID: 3df580448b26
Revises: 44fb4b97a766
Create Date: 2022-02-13 11:20:38.442251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df580448b26'
down_revision = '44fb4b97a766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('services_id', sa.Integer(), nullable=False),
    sa.Column('nomadvanplace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nomadvanplace_id'], ['nomadvanplace.id'], ),
    sa.ForeignKeyConstraint(['services_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('services_nomadvanplace_fkey', 'services', type_='foreignkey')
    op.drop_column('services', 'nomadvanplace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('nomadvanplace', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('services_nomadvanplace_fkey', 'services', 'nomadvanplace', ['nomadvanplace'], ['id'])
    op.drop_table('services_relationship')
    # ### end Alembic commands ###
