"""empty message

Revision ID: f73e4c7daa76
Revises: 9ddb31778b69
Create Date: 2022-03-24 18:51:28.594512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73e4c7daa76'
down_revision = '9ddb31778b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'location',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'location',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
